name: Run API tests
on:
  workflow_dispatch: # Manually trigger the workflow
  pull_request:
    branches:
      - main
      - v-test
      - feat/ui
  push:
    branches:
      - main
      - v-test
      - feat/ui
jobs:
  test-api:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # container:
    #   image: mcr.microsoft.com/playwright:v1.50.1-noble

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install browsers
      # - name: Install browsers
      # run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright install --with-deps --only-shell chrome
      # run: npm install --save-dev @playwright/test
      # Run [API] [SMOKE] tests
      - name: Run Playwright API tests
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          HEADLESS: ${{ secrets.HEADLESS }}
          SLACK_NOTIFICATION_URL: ${{ secrets.SLACK_NOTIFICATION_URL }}
          SALES_PORTAL_URL: ${{ secrets.SALES_PORTAL_URL }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: npm run api:smoke
        continue-on-error: true

      #   # Upload api html report
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: html-report
      #     path: ./src/report/html
      #     retention-days: 5

      # Create Allure report
      - name: Create Allure report
        run: npm run report:generate

      # Save allure report into artifacts
      - name: Save Allure report
        uses: actions/upload-artifact@v4
        with:
          name: api-smoke-report
          path: ./allure-report

        # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir: ./src/report/html
          publish_dir: ./allure-report
          destination_dir: report

  # test-ui:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*

  #     # Install dependencies
  #     - name: Install dependencies
  #       run: npm ci

  #     # Install pw
  #     - name: Install browsers
  #       run: npx playwright install --with-deps chromium

  #     # Run [UI] [SMOKE] tests
  #     - name: Run Playwright UI tests
  #       env:
  #         ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  #         ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  #         HEADLESS: ${{ secrets.HEADLESS }}
  #         SLACK_NOTIFICATION_URL: ${{ secrets.SLACK_NOTIFICATION_URL }}
  #         SALES_PORTAL_URL: ${{ secrets.SALES_PORTAL_URL }}
  #         SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  #       run: npm run ui:smoke
  #       continue-on-error: true

  #       # Upload api html report
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: html-report
  #         path: ./src/report/html
  #         retention-days: 5

  #       # Deploy to GitHub Pages
  #     - name: Deploy to GitHub Pages
  #       if: success()
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./src/report/html
  #         destination_dir: report
